# Generated by Django 3.2.5 on 2021-07-08 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripción', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Clasificacion_e',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Contenido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('fecha_estreno', models.DateField()),
                ('original_netflix', models.BooleanField()),
                ('descripcion', models.CharField(max_length=50)),
                ('duracion', models.CharField(max_length=50, null=True)),
                ('tipo', models.CharField(choices=[('P', 'Pelicula'), ('S', 'Serie')], default='P', max_length=2)),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netflixapp.ciudad')),
                ('clasificacion_edad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netflixapp.clasificacion_e')),
            ],
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('contrasena', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('fecha_nacimiento', models.DateField()),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('N/A', 'No aplica')], default='M', max_length=3)),
                ('telefono', models.IntegerField()),
                ('fecha_creacion', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Episodio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
                ('duracion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Idioma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Membresia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_membresia', models.CharField(max_length=50)),
                ('precio', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripción', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Persona_Contenido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombTrab', models.CharField(max_length=50)),
                ('ApellidoTrab', models.CharField(max_length=50)),
                ('Annio_experiencia', models.DateField()),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('N/A', 'No aplica')], default='M', max_length=3)),
                ('Es_actor', models.BooleanField()),
                ('Es_director', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_dispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripción', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Temporada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
                ('contenido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netflixapp.contenido')),
            ],
        ),
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ccv', models.IntegerField()),
                ('vencimiento', models.DateField()),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netflixapp.cuenta')),
            ],
        ),
        migrations.CreateModel(
            name='Subscripcion_cuenta',
            fields=[
                ('fecha_inicio', models.DateField(auto_now=True, primary_key=True, serialize=False)),
                ('fecha_fin', models.DateField(null=True)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netflixapp.cuenta')),
                ('membresia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netflixapp.membresia')),
            ],
        ),
        migrations.CreateModel(
            name='Subscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateTimeField()),
                ('fin_servicio', models.DateTimeField()),
                ('total', models.IntegerField()),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netflixapp.cuenta')),
                ('membresia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netflixapp.membresia')),
                ('tarjeta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netflixapp.tarjeta')),
            ],
        ),
        migrations.CreateModel(
            name='Premio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('ano_ganadora', models.DateField()),
                ('contenido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netflixapp.contenido')),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netflixapp.cuenta')),
            ],
        ),
        migrations.AddField(
            model_name='membresia',
            name='cuentas',
            field=models.ManyToManyField(through='netflixapp.Subscripcion_cuenta', to='netflixapp.Cuenta'),
        ),
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_visualizacion', models.TimeField()),
                ('hora_finalizacion', models.TimeField()),
                ('fecha', models.DateField()),
                ('calificacion', models.IntegerField(default=0)),
                ('Episodio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='netflixapp.episodio')),
                ('Perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netflixapp.perfil')),
                ('contenido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netflixapp.contenido')),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netflixapp.dispositivo')),
            ],
        ),
        migrations.AddField(
            model_name='episodio',
            name='temporada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netflixapp.temporada'),
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netflixapp.tipo_dispositivo'),
        ),
        migrations.CreateModel(
            name='Dirige',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netflixapp.contenido')),
                ('persona_contenido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netflixapp.persona_contenido')),
            ],
        ),
        migrations.AddField(
            model_name='contenido',
            name='generos',
            field=models.ManyToManyField(to='netflixapp.Genero'),
        ),
        migrations.AddField(
            model_name='contenido',
            name='idioma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netflixapp.idioma'),
        ),
        migrations.AddField(
            model_name='contenido',
            name='subcripciones',
            field=models.ManyToManyField(to='netflixapp.Subscripcion'),
        ),
        migrations.AddField(
            model_name='ciudad',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netflixapp.pais'),
        ),
        migrations.CreateModel(
            name='Actua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_protagonista', models.BooleanField()),
                ('contenido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netflixapp.contenido')),
                ('persona_contenido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netflixapp.persona_contenido')),
            ],
        ),
    ]
